services:
  sistema:
    build: sistema
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://electricidad:3306/electricidad?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: app
      DB_PASSWORD: app123

      APP_ADMIN_USER: admin
      APP_ADMIN_PASS: ${ADMIN_PASS}
      APP_EMPLEADO_USER: empleado
      APP_EMPLEADO_PASS: ${EMPLEADO_PASS}

    restart: always
    depends_on:
      electricidad:
        condition: service_healthy

  electricidad:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: app123
      MYSQL_DATABASE: electricidad
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
